[mypy]
python_version = 3.11
ignore_missing_imports = True
follow_imports = silent
warn_redundant_casts = True
warn_unused_ignores = False
no_implicit_optional = True
check_untyped_defs = False
disallow_untyped_defs = False
plugins = pydantic.mypy

# Third-party / generated code we don't type-check strictly.
[mypy-alembic.*]
ignore_errors = True
